Module6 task1
htmlacademy-ecmascript/1145499-cinemaddict-14 pull request #10
Opened 2021-04-28 11:14 UTC by Filippoussis

2021-04-28 12:41 UTC, AlexMasterov requested changes

2021-04-28 12:41 UTC, AlexMasterov commented on src/view/film-details.js
> +  static parseFilmToState(film) {
[`Д 8`](https://up.htmlacademy.ru/ecmascript/14/criteries#d8)
> Методы внутри классов упорядочены
```
5. Статические методы
```

2021-04-28 12:41 UTC, AlexMasterov commented on src/view/film-details.js
> +  _setInnerHandlers() {
[`Д 8`](https://up.htmlacademy.ru/ecmascript/14/criteries#d8)
> Методы внутри классов упорядочены
```
3. Основные методы класса
```

2021-04-28 12:41 UTC, AlexMasterov commented on src/view/film-details.js
> +export default class FilmDetails extends SmartView {
При выборе эмоции перерисовывается весь попап, но самое неприятное для пользователя — это скролл в начало (наверх) страницы.

<details>
<summary>view/smart.js</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/e4f96c644f0bc70afe10c5e43b5dac9a488bf787/src/view/smart.js#L28-L37
</details>

Советую это решить хотя бы самым простым способом: в `Smart.updateElement` запомнить и восстановить одно значение `.scrollTop`.

> Также можно _рискнуть_ разделить компонент на части

2021-04-28 12:41 UTC, AlexMasterov commented on src/view/film-details.js
>  const renderCommentsTemplate = (comments) => {
`render`CommentsTemplate 🤔

2021-04-28 12:41 UTC, AlexMasterov commented on src/view/films-sort.js
>    _sortTypeChangeHandler(evt) {
<details>
<summary>view/films-sort.js</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/e4f96c644f0bc70afe10c5e43b5dac9a488bf787/src/view/films-sort.js#L36
https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/e4f96c644f0bc70afe10c5e43b5dac9a488bf787/src/view/films-sort.js#L42
https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/e4f96c644f0bc70afe10c5e43b5dac9a488bf787/src/view/films-sort.js#L44
https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/e4f96c644f0bc70afe10c5e43b5dac9a488bf787/src/view/films-sort.js#L47
</details>

**4x** `evt.target`

2021-04-28 12:41 UTC, AlexMasterov commented on src/view/film-details.js
<details>
<summary>film-details.js</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/e4f96c644f0bc70afe10c5e43b5dac9a488bf787/src/view/film-details.js#L86-L113
</details>


<details>
<summary>film-details.js</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/e4f96c644f0bc70afe10c5e43b5dac9a488bf787/src/view/film-details.js#L121-L122
https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/e4f96c644f0bc70afe10c5e43b5dac9a488bf787/src/view/film-details.js#L124-L125
https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/e4f96c644f0bc70afe10c5e43b5dac9a488bf787/src/view/film-details.js#L127-L128
</details>

<details>
<summary>view/film-details.js</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/e4f96c644f0bc70afe10c5e43b5dac9a488bf787/src/view/film-details.js#L150-L153
https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/e4f96c644f0bc70afe10c5e43b5dac9a488bf787/src/view/film-details.js#L155-L158
https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/e4f96c644f0bc70afe10c5e43b5dac9a488bf787/src/view/film-details.js#L160-L163
https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/e4f96c644f0bc70afe10c5e43b5dac9a488bf787/src/view/film-details.js#L165-L168
</details>

Генерация похожей разметки дублируется в многих местах шаблона.

2021-04-29 04:20 UTC, Filippoussis commented on src/view/film-details.js
>  const renderCommentsTemplate = (comments) => {
rename -> createCommentsTemplate

2021-04-30 15:06 UTC, Filippoussis commented on src/view/smart.js
> +  updateElement() {
изменил на newView, prevView

2021-05-01 02:16 UTC, AlexMasterov commented on src/view/smart.js
> +  updateElement() {
Сейчас в проекте суффикс `View` используется для экземпляров классов (= объектов), которые играют _роль_ компонентов Представления (`View` в `MVP`).

Возможно, лучше просто убрать суффикс или заменить его на обобщение: _узел_ (`Node`). 

<details>
<summary>Что следует знать для вариант с Node</summary>

Для второго варианта напомню, что `Element` — это [_тип_ узла](https://developer.mozilla.org/ru/docs/Web/API/Node/nodeType) (`Node`), узел-элемент.

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/e4f96c644f0bc70afe10c5e43b5dac9a488bf787/src/view/smart.js#L30

Если посмотреть [реализацию свойства](https://source.chromium.org/chromium/chromium/src/+/refs/tags/92.0.4493.3:third_party/blink/renderer/core/dom/element.h;l=1320-1322) (неявного геттера) [Node.`parentElement`](https://developer.mozilla.org/ru/docs/Web/API/Node/parentElement) в браузера `Chromium`, то можно увидеть приведение к этому типу:

```cpp
inline Element* Node::parentElement() const {
  return DynamicTo<Element>(parentNode());
}
```
Поэтому подобная замена обобщением вполне допустима. Но также следует знать, что все наши компоненты и их утилитарные функции для DOM неявно работают с типом `Node.ELEMENT_NODE`. Работа с другим типом узла может вызвать проблемы. В этом случае мы также, но уже слегка, неверно выражаем ограничения 😃

</details>

2021-05-01 02:24 UTC, AlexMasterov commented on src/view/film-details.js
> +        localEmoji: null,
```js
emoji !== ''
```
С условием стало лучше. 

> Осталось разобраться с `null` в отсутствие значения для `localEmoji`

<details>
<summary>getCommentEmoji</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/e4f96c644f0bc70afe10c5e43b5dac9a488bf787/src/view/film-details.js#L34-L36
</details>

Теперь обрати внимание, что _вся_ полезная работа функции зависит от наличия значения в параметре. Может лучше _уровнем выше_ в отсутствие нужного значения вообще не вызывать эту функцию 😃

2021-05-01 02:35 UTC, AlexMasterov commented on src/view/film-details.js
> +      localComment: evt.target.value,
Может в этом PR сразу реализуешь безопасный ввод текста комментария?

См. [пример коммита с реализацией для демо проекта](https://github.com/htmlacademy-ecmascript/taskmanager-14/commit/40d9511233064eeaaff876bfc530b0533a933490).

2021-05-01 19:56 UTC, AlexMasterov requested changes

2021-05-01 19:56 UTC, AlexMasterov commented on src/view/film-details-info.js
> +          ${createListFilmTermsTemplate(filmDetailsTerms)}
<details>
<summary>view/film-details-info.js</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/2ec77da7b232835d712d7beebf16ce497a450d23/src/view/film-details-info.js#L4-L27
https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/2ec77da7b232835d712d7beebf16ce497a450d23/src/view/film-details-info.js#L41-L49
</details>

`Object.entries` использовал уверенно 😃
Но само решение для такой задаче очень сложное, медленное, а главное негибкое. 

> Если оставить, то придаться исправлять замечания по спекулятивным критериям

<details>
<summary>Покажи, как лучше упростить</summary>

```js
const createDetailsRowTemplate = (term, cell) => (
  `<tr class="film-details__row">
    <td class="film-details__term">${term}</td>
    <td class="film-details__cell">${cell}</td>
  </tr>`
);
```
```js
// createFilmDetailsInfoTemplate
const genreTitle = genres.length > 1 ? 'Genres' : 'Genre';
const genreTemplate = createGenreTemplate(genres);

`<table class="film-details__table">
  ${createDetailsRowTemplate('Director', director)}
  ${createDetailsRowTemplate(genreTitle, genreTemplate)}
  // ...
</table>`
```
</details>

2021-05-01 19:56 UTC, AlexMasterov commented on src/view/film-details-new-comment.js
> +        <textarea class="film-details__comment-input" placeholder="Select reaction below and write comment here" name="comment">${he.encode(localComment)}</textarea>
`${he.encode(localComment)}`

Применил только в нужном месте 👍🏻

2021-05-01 19:56 UTC, AlexMasterov commented on src/view/film-details-controls.js
> +      ${createControlsTemplate(CONTROLS, controlState)}
<details>
<summary>view/film-details-controls.js</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/2ec77da7b232835d712d7beebf16ce497a450d23/src/view/film-details-controls.js#L3-L24
</details>

Сложно 😟

См. [пример](https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/2ec77da7b232835d712d7beebf16ce497a450d23/src/view/film-card.js#L45-L49).

Попробуй похожим образом реализовать функцию для созданию шаблона с кнопкой с таким интерфейсом:

```js
const createControlTemplate= (name, title, isChecked = false) => { ... }
```

```js
${createControlTemplate('watchlist', 'Add to watchlist', isWatchlist)}
```

2021-05-01 20:02 UTC, AlexMasterov requested changes

2021-05-01 20:02 UTC, AlexMasterov commented on src/presenter/film-details.js
> +    this._filmDetailsCloseView.setCloseButtonClickHandler(this._removeFilmDetails);
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/116793735-2fb1cb80-aad1-11eb-8569-dd3814eaf603.png)

</details>

Попап должен закрывать по нажатию на крестик, а не область с ним.

Нужно разобраться и исправить.

2021-05-01 20:05 UTC, AlexMasterov requested changes

2021-05-01 20:05 UTC, AlexMasterov commented on src/view/film-details-new-comment.js
> +const createFilmDetailsNewCommentTemplate = (state) => {
<details>
<summary>Сейчас</summary>

![image](https://user-images.githubusercontent.com/700213/116793786-90410880-aad1-11eb-86c9-958fb95fd560.png)

</details>

<details>
<summary>Ожидание (markup/popup-add-comment.html)</summary>

![image](https://user-images.githubusercontent.com/700213/116793775-7d2e3880-aad1-11eb-99b9-9c871108cebb.png)

</details>

Нужно доработать: выбранная эмоция должна быть "активна" с помощью добавления спец. класса.

2021-05-02 02:36 UTC, Filippoussis commented on src/view/film-details-comments.js
> +export default class createFilmDetailsComments extends Abstract {
странная ошибка) видимо скопипастил с темплейта, буду внимательнее

2021-05-02 02:59 UTC, Filippoussis commented on src/presenter/film-details.js
> +    this._filmDetailsCloseView.setCloseButtonClickHandler(this._removeFilmDetails);
_handleFilmDetails() {
    this._removeFilmDetails();
  }

2021-05-02 08:28 UTC, Filippoussis commented on src/presenter/film-details.js
> +    this._filmDetailsCloseView.setCloseButtonClickHandler(this._removeFilmDetails);
this.getElement().firstElementChild

2021-05-02 08:34 UTC, AlexMasterov commented on src/presenter/film-details.js
> +    this._filmDetailsCloseView.setCloseButtonClickHandler(this._removeFilmDetails);
> this.getElement().firstElementChild

Для защиты проекта главное чтобы работало 😃

Но если разметка (без тебя) изменится, то это перестанет работать.

2021-05-02 08:44 UTC, AlexMasterov commented
👍🏻

2021-05-02 08:44 UTC, merged