Меняй-удаляй (часть 1)
htmlacademy-ecmascript/1145499-cinemaddict-14 pull request #11
Opened 2021-05-11 14:47 UTC by Filippoussis

---
:mortar_board: [Меняй-удаляй (часть 1)](https://up.htmlacademy.ru/ecmascript/14/user/1145499/tasks/12)

:boom: https://htmlacademy-ecmascript.github.io/1145499-cinemaddict-14/11/

2021-05-11 16:40 UTC, AlexMasterov requested changes
> Files changed `33` (+`1,091` −`322`)

Уфф.

Местами неоправданно сложно и снова много дублирования 😃

2021-05-11 16:40 UTC, AlexMasterov commented on src/presenter/all-films.js
> +    if (resetRenderedFilmCount) {
<details>
<summary>presenter/all-films.js</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/ea62e030fbaf30e795cc96cbde626118e788dd07/src/presenter/all-films.js#L171-L175
</details>

[`Д 14`](https://up.htmlacademy.ru/ecmascript/14/criteries#d14)
> Там, где возможно, в присвоении значения вместо `if` используется тернарный оператор

2021-05-11 16:40 UTC, AlexMasterov commented on src/presenter/all-films.js
> +      this._renderedFilmCount = Math.min(filmCount, this._renderedFilmCount);
<details>
<summary>presenter/all-films.js</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/ea62e030fbaf30e795cc96cbde626118e788dd07/src/presenter/all-films.js#L160
</details>

`filmCount` используется только в случае выполнения условия.

2021-05-11 16:40 UTC, AlexMasterov commented on src/presenter/all-films.js
> +export default class AllFilms {
<details>
<summary>presenter/all-films.js</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/ea62e030fbaf30e795cc96cbde626118e788dd07/src/presenter/all-films.js#L159
https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/ea62e030fbaf30e795cc96cbde626118e788dd07/src/presenter/all-films.js#L183
</details>

_renderFilms`Board`

В этом проекте не нахожу _доску_, только _списки_ с фильмами 🤔

2021-05-11 16:40 UTC, AlexMasterov commented on src/presenter/films-total.js
> +    this._renderFilmsTotal();
<details>
<summary>init</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/ea62e030fbaf30e795cc96cbde626118e788dd07/src/presenter/films-total.js#L13-L29
</details>

Увлекся 😃

2021-05-11 18:45 UTC, Filippoussis commented on src/utils/observer.js
> +export default class Observer {
export default class Observer {
  constructor() {
    this._listeners = [];
  }

  subscribe(listener) {
    this._listeners.push(listener);
  }

  unsubscribe(listener) {
    this._listeners = this._listeners.filter((existedListener) => existedListener !== listener);
  }

  _notify(event, payload) {
    this._listeners.forEach((listener) => listener(event, payload));
  }
}

2021-05-11 18:46 UTC, Filippoussis commented on src/const.js
> +  FAVORITES: 'isFavorite',
оставляем?) не понял

2021-05-11 19:16 UTC, AlexMasterov commented on src/utils/observer.js
> +export default class Observer {
Годно 👍🏻

2021-05-11 19:18 UTC, AlexMasterov commented on src/presenter/screen.js
> +  _renderNoFilms() {
> мне казалось это условие относится к общему списку фильмов (общей базе), а не распространяется и на фильтры Watchlist, History, Favorite? там ведь 0 стоят)

Думаю также. Сам хотел уточнить.

> задал вопрос **Создателям**

Хорошо, опередил меня с этим вопросов к ним 😄

2021-05-11 19:23 UTC, Filippoussis commented on src/presenter/screen.js
> +    if (this._getFilms().length > 0) {
isEmpty() {
    return Boolean(this._items.length);
  }

2021-05-11 19:32 UTC, Filippoussis commented on src/presenter/all-films.js
> +      this._renderedFilmCount = Math.min(filmCount, this._renderedFilmCount);
else {
      this._renderedFilmCount = Math.min(this._getFilms().length, this._renderedFilmCount);
    }

2021-05-11 19:35 UTC, Filippoussis commented on src/presenter/all-films.js
> +    if (resetRenderedFilmCount) {
this._renderedFilmCount = resetRenderedFilmCount ? FilmCount.STEP : Math.min(this._getFilms().length, this._renderedFilmCount);

2021-05-11 19:37 UTC, AlexMasterov commented on src/presenter/all-films.js
> +    if (resetRenderedFilmCount) {
```js
this._renderedFilmCount = resetRenderedFilmCount 
  ? FilmCount.STEP 
  : Math.min(this._getFilms().length, this._renderedFilmCount);
```

2021-05-12 04:17 UTC, Filippoussis commented on src/presenter/films-total.js
> +    this._renderFilmsTotal();
ну я догадываюсь что данные база фильмов будет получена 1 раз, но я предусмотрел если количество фильмов будет в базе меняться, тогда обмен данными произойдет через презентер)

2021-05-13 20:32 UTC, Filippoussis commented on src/presenter/film-details-comments-list.js
> +    const filmComments = this._film.comments.map((commentId) => this._getComments().find((item) => item.id === commentId));
оптимизацию выполню чуть позднее, не нашел пока как создать структуру

2021-05-13 20:33 UTC, Filippoussis commented on src/presenter/film-card.js
Д11
export const updateFilmProperty = (film, prop) => {
  return (
    Object.assign(
      {},
      film,
      {
        [prop]: !film[prop],
      },
    )
  );
};

2021-05-13 20:35 UTC, Filippoussis commented on src/presenter/film-card.js
2 оптимизация пока в работе,
цель при апдейте фильма понять на какой вкладке фильтра я нахожусь, и от этого делаю либо частичный апдейт, либо всего списка

2021-05-13 22:23 UTC, AlexMasterov commented on src/presenter/film-card.js
> цель при апдейте фильма понять на какой вкладке фильтра я нахожусь, и от этого делаю либо частичный апдейт, либо всего списка

Наличие проверки состояние фильтра — уже хорошо. 
В остальном же мы остались заложникам решения из демо проекта 😃

2021-05-13 23:27 UTC, AlexMasterov approved these changes
Сейчас у тебя работает всё, что формально требуется (и не требуется) для ТЗ от этого задания 😃👍🏻

Пожалуйста, замечание в остатке учти при выполнении следующего задания.

> В отсутствие свободного времени прошу не пытаться учесть необязательные замечания

2021-05-13 23:27 UTC, AlexMasterov commented on src/view/films-filter.js
> +  const elementCount = type !== FilterType.ALL ? `<span class="main-navigation__item-count">${count}</span>` : '';
Не используй `element`.

main-navigation__`item`-`count`

```diff
- elementCount 
+ itemCount
```

2021-05-13 23:27 UTC, AlexMasterov commented on src/presenter/film-details-comments-list.js
> +  _handleCommentDeleteClick(deletedCommentId) {
<details>
<summary>_handleCommentDeleteClick</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/fb3955cc0da02acfdc167f213354524c8b6fc0a2/src/presenter/film-details-comments-list.js#L55-L70
</details>

Возможно, что после получения данных с сервера, потребуется переделать это место.

Главное, что всё работает по ТЗ 😃

2021-05-13 23:27 UTC, AlexMasterov commented on src/utils/observer.js
> +  _notify(event, payload) {
`event`

[`Б 30`](https://up.htmlacademy.ru/ecmascript/14/criteries#b30)
> Нельзя пользоваться глобальной переменной `event`

> _Затенение_ переменных критерием не учитывается

2021-05-13 23:29 UTC, merged

2021-05-14 04:16 UTC, Filippoussis commented on src/presenter/film-details-comments-list.js
> +    const filmComments = this._film.comments.map((commentId) => this._getComments().find((item) => item.id === commentId));
спасибо!