Module8 task1
htmlacademy-ecmascript/1145499-cinemaddict-14 pull request #12
Opened 2021-05-15 12:56 UTC by Filippoussis

2021-05-15 13:49 UTC, AlexMasterov requested changes

2021-05-15 13:49 UTC, AlexMasterov commented on src/model/films.js
> +  static adaptToClient(item) {
<details>
<summary>model/films.js</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/5f8f34d150de690425a7e0b819c0c4888e5273be/src/model/films.js#L39-L59
</details>

**XX** `item`.`film_info`.`*`

2021-05-15 13:49 UTC, AlexMasterov commented on src/model/films.js
>  }
<details>
<summary>model/films.js</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/5f8f34d150de690425a7e0b819c0c4888e5273be/src/model/films.js#L35-L61
https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/5f8f34d150de690425a7e0b819c0c4888e5273be/src/model/films.js#L70-L98
</details>

<details>
<summary>model/films.js</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/5f8f34d150de690425a7e0b819c0c4888e5273be/src/model/films.js#L63-L64
https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/5f8f34d150de690425a7e0b819c0c4888e5273be/src/model/films.js#L100-L116
</details>

В обоих случаях проще и дешевле создать новый объект, чем заниматься его копированием и удалять свойства.

2021-05-15 13:49 UTC, AlexMasterov commented on src/presenter/all-films.js
> +const actionTypetoFilterType = {
👍🏻

2021-05-15 13:49 UTC, AlexMasterov commented on src/presenter/all-films.js
>  export default class AllFilms {
<details>
<summary>Покажи, что опять можно улучшить</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/5f8f34d150de690425a7e0b819c0c4888e5273be/src/presenter/all-films.js#L55

Советую для хранения презентеров вместо объекта попробовать использовать [`Map`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Map).

> Текущие авторы курса (с подачи наставников) давно приняли решение использовать `Map`, но в сам курс и демо проект он будет добавлен только в след. интенсиве

Для замены достаточно освоить след. методы:

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/5f8f34d150de690425a7e0b819c0c4888e5273be/src/presenter/all-films.js#L84

См. [Map.p.`get`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Map/get).

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/5f8f34d150de690425a7e0b819c0c4888e5273be/src/presenter/all-films.js#L130

См. [Map.p.`set`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Map/set).

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/5f8f34d150de690425a7e0b819c0c4888e5273be/src/presenter/all-films.js#L211-L213

См. [Map.p.`forEach`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Map/forEach).

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/5f8f34d150de690425a7e0b819c0c4888e5273be/src/presenter/all-films.js#L215

См. [Map.p.`clear`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Map/clear).

См. также [Map.p.`size`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Map/size).
</details>

2021-05-15 13:49 UTC, AlexMasterov commented on src/main.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/118363519-70afe280-b59d-11eb-9c20-10704899beb5.png)

</details>

Нет комментариев.

При открытии попапа выбрасывается исключение (ошибка):
```
film-details.js:48 Uncaught TypeError: Cannot read property 'getComments' of undefined
```
Б2

2021-05-15 13:49 UTC, AlexMasterov commented on src/main.js
Если применить фильтр и открыть попап карточки из списка, а потом удалить все карточки по фильтру списка, включая карточку самого попапа, то отметка другой кнопки фильтрации в попапе приведёт к ошибке:

```
all-films.js:84 Uncaught (in promise) TypeError: Cannot read property 'init' of undefined
    at AllFilms._handleModelEvent (all-films.js:84)
```
Б2

2021-05-15 13:49 UTC, AlexMasterov commented on src/main.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/118362840-0d708100-b59a-11eb-8369-d0f8922bc4a4.png)
![image](https://user-images.githubusercontent.com/700213/118362848-1c573380-b59a-11eb-92d1-add94cccac50.png)

</details>

Если применить фильтр и открыть попап карточки из списка, а потом удалить все карточки по фильтру списка, включая карточку самого попапа, то отметка текущего фильтра вернет карточку в список, но она будет спрятана за кнопкой `Show More`.

> Проблема также актуальна для демо проекта 🐛

2021-05-15 13:49 UTC, AlexMasterov commented on src/presenter/all-films.js
>  export default class AllFilms {
<details>
<summary>presenter/all-films.js</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/5f8f34d150de690425a7e0b819c0c4888e5273be/src/presenter/all-films.js#L56
</details>

<details>
<summary>presenter/all-films.js</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/5f8f34d150de690425a7e0b819c0c4888e5273be/src/presenter/all-films.js#L122-L131
https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/5f8f34d150de690425a7e0b819c0c4888e5273be/src/presenter/all-films.js#L137-L147
</details>

Лишняя логика и дублирование.

Достаточно хранить и обрабатывать _одну_ карточку попапа.

2021-05-15 13:49 UTC, AlexMasterov commented on src/presenter/all-films.js
>        this._changeMode,
У тебя получилось избавить от зависимости модели с фильтром, но простые компоненты продолжают много знать и заниматься не своим делом.

`this._showFilmDetails` не нужен.

<details>
<summary>presenter/film-card.js</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/5f8f34d150de690425a7e0b819c0c4888e5273be/src/presenter/film-card.js#L33-L36
</details>

В карточке достаточно сделать это:
```js
this._sectionView.setClickHandler(() => {
  this._changeMode(this._film);
});
```
Открытие попапа следует делать в `AllFilms`:
```js
this._openPopup(this._film);
```

2021-05-15 13:49 UTC, AlexMasterov commented on src/main.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/118363244-1d896000-b59c-11eb-906f-1694572ed419.png)
![image](https://user-images.githubusercontent.com/700213/118363252-25e19b00-b59c-11eb-90ce-9c3b4ecbd722.png)

</details>

Если у _одной_ карточки открыть попап и отметить фильтр у _другой_ из списка, то изменения начинают синхронизироваться с папапом чужой карточки.

2021-05-15 13:49 UTC, AlexMasterov commented on src/utils/time.js
> +  return `${hours}h ${minutes}m`;
А если фильм длится меньше часа 🤔

2021-05-15 13:49 UTC, AlexMasterov commented on src/main.js
Если повторно открыть карточку, то перестает работать выбор эмоции.

2021-05-15 13:56 UTC, AlexMasterov requested changes

2021-05-15 13:56 UTC, AlexMasterov commented on src/main.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/118363693-4579c300-b59e-11eb-9523-521eb2d6a01a.png)

</details>

Изменения между карточкой и попапом синхронизируются только один раз и при его первом открытии. На втором всё перестает работать.

2021-05-16 05:58 UTC, Filippoussis commented on src/main.js
ооооо, как же так, все работало, проверял, видимо в конце что то поправил и не протестировал) исправляю...

2021-05-16 06:20 UTC, Filippoussis commented on src/main.js
нашел, от зависимости от фильтр модели избавился, но в некоторых компонентах забыл удалить прокидываемые props, устранил

2021-05-17 03:39 UTC, Filippoussis commented on src/main.js
перепроверил, все работает после устранения предыдущих ошибок - удаления ненужных props

2021-05-17 03:39 UTC, Filippoussis commented on src/main.js
перепроверил, все работает после устранения предыдущих ошибок - удаления ненужных props

2021-05-17 03:42 UTC, Filippoussis commented on src/presenter/all-films.js
>  export default class AllFilms {
по сути у меня хранится всегда 1 попап там, и при открытии другого тот удаляется.

2021-05-17 03:51 UTC, Filippoussis commented on src/utils/time.js
> +  return `${hours}h ${minutes}m`;
export const getFormattedTime = (time) => {
  const hours = Math.trunc(time/MINUTES_PER_HOUR);

  const humanisedHours = hours > 0 ? `${hours}h` : '';
  const humanisedMinutes = `${time - hours*MINUTES_PER_HOUR}m`;

  return `${humanisedHours} ${humanisedMinutes}`;
};

2021-05-17 05:36 UTC, Filippoussis commented on src/main.js
проблему вижу, буду подумаю как устранять перед защитой

2021-05-17 05:36 UTC, Filippoussis commented on src/main.js
проблему вижу, подумаю как устранять перед защитой

2021-05-17 05:37 UTC, Filippoussis commented on src/main.js
проблему вижу, подумаю как устранять перед защитой

2021-05-17 06:14 UTC, AlexMasterov commented on src/main.js
> проблему вижу, подумаю как устранять перед защитой

🤔

<details>
<summary>Подскажи проблемное место</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/9e568e967713abb603e3cf0a6fed4e9acc6132eb/src/presenter/all-films.js#L220

```js
Math.min(1, this._renderedFilmCount) // 0
```
</details>

2021-05-17 06:15 UTC, AlexMasterov commented on src/presenter/all-films.js
>  export default class AllFilms {
> по сути у меня **хранится всегда `1` попап** там, и при открытии другого тот удаляется.

Тогда зачем использовать структуру 😃

2021-05-17 06:23 UTC, AlexMasterov commented on src/main.js
> проблему вижу, подумаю как устранять перед защитой

🤔

<details>
<summary>Подскажи проблемное место</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/9e568e967713abb603e3cf0a6fed4e9acc6132eb/src/presenter/all-films.js#L83

Если воспроизвести проблему, то в этом месте в момент вызова не будет презентера:
```js
this._filmPresenterMap.get(data.id) // undefined
```
**Наличие презентера не проверяется**, вызов метода `.init` происходит в любом случае.
</details>

2021-05-17 06:32 UTC, AlexMasterov commented
По заданию всё 👍🏻

Подсказки к замечаниям оставил, попробуй с ними еще раз самостоятельно исправить.

2021-05-17 06:33 UTC, merged

2021-05-17 06:50 UTC, Filippoussis commented on src/main.js
мне кажется при открытом попапе , мы как бы не должны вообще контролы на другой карточке нажимать) я думаю они должны быть задизейблены, и уж если мы добрались до миникарточки , то можем только открыть ее, что приведет к закрытию текущего попапа и открытию нового.

2021-05-17 07:16 UTC, AlexMasterov commented on src/main.js
> думаю при открытии попапа ставить disabled контролам миникарточек, а при закрытии попапа снимать

Уточню у авторов. Вообще это хорошие дополнение для ТЗ 👍🏻

2021-05-19 17:34 UTC, Filippoussis commented on src/main.js
this._renderedFilmCount = resetRenderedFilmCount || this._renderedFilmCount === 0
      ? FilmCount.STEP
      : Math.min(this._getFilms().length, this._renderedFilmCount);

2021-05-19 17:52 UTC, Filippoussis commented on src/main.js
if (this._renderedFilmCount === 0) {
      this._filmDetailsPresenterMap.forEach((presenter) => presenter.resetView());
 }
решил при исключении последней карточки из выбранного фильма закрывать попап автоматически

2021-05-19 17:53 UTC, Filippoussis commented on src/main.js
if (this._renderedFilmCount === 0) {
this._filmDetailsPresenterMap.forEach((presenter) => presenter.resetView());
}
решил при исключении последней карточки из выбранного фильма закрывать попап автоматически