Module8 task2
htmlacademy-ecmascript/1145499-cinemaddict-14 pull request #13
Opened 2021-05-19 17:59 UTC by Filippoussis

2021-05-20 01:03 UTC, AlexMasterov requested changes

2021-05-20 01:03 UTC, AlexMasterov commented on src/presenter/all-films.js
<details>
<summary>view/film-details-new-comment.js</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/44c9535e82171c03fa6c8f441af684169da9d72b/src/presenter/film-details.js#L196
https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/44c9535e82171c03fa6c8f441af684169da9d72b/src/view/film-details-new-comment.js#L111
</details>

~Б5

Желательно создать для _ключей клавиатуры_ `Escape` и `Enter` создать _перечисление_, а для определений событий _функции_.

2021-05-20 03:47 UTC, AlexMasterov requested changes

2021-05-20 03:47 UTC, AlexMasterov commented on src/view/film-details-new-comment.js
> +    document.addEventListener('keydown', this._formSubmitHandler);
'keydown' !== this._form`Submit`Handler

Д4

2021-05-20 03:49 UTC, AlexMasterov requested changes

2021-05-20 03:49 UTC, AlexMasterov commented on src/view/film-details-new-comment.js
> +  setFormSubmitHandler(callback) {
Д8

2021-05-20 03:50 UTC, Filippoussis commented on src/presenter/film-details-comments.js
> +    this._listView.actionOnError();
handleActionOnError() {
    this._listView.errorHandler();
 }

2021-05-20 03:53 UTC, AlexMasterov commented on src/presenter/film-details-comments.js
> +    this._listView.actionOnError();
https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/44c9535e82171c03fa6c8f441af684169da9d72b/src/view/film-details-comments-list.js#L52-L55

Это не _коллбэк_, а простой метод, который явно вызывается в коде.

> handleActionOnError() {
> this._listView.errorHandler();
> }

Б10

2021-05-20 04:38 UTC, Filippoussis commented on src/presenter/film-details-comments.js
> +    this._listView.actionOnError();
setErrorEffect() {
   this._listView.showErrorEffect();
}

2021-05-20 05:58 UTC, Filippoussis commented on src/view/film-details-comments-list.js
> +    this._target = evt.target;
this._target = null;

2021-05-20 09:25 UTC, Filippoussis commented on src/presenter/all-films.js
подумаю еще тут до защиты, пока задал вопрос авторам как они видят продолжение того что карточек уже на доске в выбранном фильтре нет, а мы все еще с открытым попапом пытаемся нажимать другие контролы, по хорошему я бы закрывал автоматом, хотя может мне так конечно проще) но если мы фаворитах и исключили ее,  то логичнее и закрыть попап, ну или может доска должна переходить в режим ВСЕ ФИЛЬМЫ)

2021-05-20 10:14 UTC, AlexMasterov commented on src/view/film-details-new-comment.js
> +    if (evt.key === KeyName.ENTER && (evt.ctrlKey || evt.metaKey)) {
Вижу, что функции по типу `isEscapeEvent` решил не создать: вместо чтения с фокусом на логике приложения продолжим спотыкаться взглядом об эти условия 😃

2021-05-20 10:19 UTC, AlexMasterov commented on src/view/film-card.js
> +  disableConrols(isDisabled) {
`isDisabled`

Функции с булевыми флагами почти всегда нарушают [Принцип единственной ответственности](https://www.youtube.com/watch?v=SKwchYgaJN8#t=21m23s).

2021-05-20 10:22 UTC, AlexMasterov commented on src/view/film-details-new-comment.js
> +    this._callback.keyDownForm = callback;
this._callback.`keyDown`Form

Б10

2021-05-20 10:23 UTC, merged

2021-05-20 10:32 UTC, Filippoussis commented on src/const.js
> +export const KeyName = {
спасибо) я на самом деле сидел и выбирал между KeyBoardKey и KeyName) мне показалось в первом случае 2 раза в слове  Key будет избыточным) намек не понял, буду внимательнее

2021-05-20 10:43 UTC, AlexMasterov commented on src/const.js
> +export const KeyName = {
> Возможно, что изначально это было сложным существительным: `Key` `Board` (= клавишная доска).

Сейчас `Keyboard` (в такой записи) — [целое слово](https://dictionary.cambridge.org/ru/%D1%81%D0%BB%D0%BE%D0%B2%D0%B0%D1%80%D1%8C/%D0%B0%D0%BD%D0%B3%D0%BB%D0%BE-%D1%80%D1%83%D1%81%D1%81%D0%BA%D0%B8%D0%B9/keyboard).

Но если этого не знать, то твой выбор вполне логичен 😃

2021-05-24 08:32 UTC, Filippoussis commented on src/view/film-card.js
> +  disableConrols(isDisabled) {
здесь еще думаю над лучшим решением