Module7 task2
htmlacademy-ecmascript/1145499-cinemaddict-14 pull request #14
Opened 2021-05-24 08:37 UTC by Filippoussis

2021-05-24 11:20 UTC, AlexMasterov requested changes

2021-05-24 11:20 UTC, AlexMasterov commented on src/view/user-statistic.js
> +  _getFiltredStats(films, filter) {
<details>
<summary>presenter/screen.js</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/81dc005a1e8b31df814e5542906c55bcc5854ae1/src/presenter/screen.js#L74
</details>

<details>
<summary>view/user-statistic.js</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/81dc005a1e8b31df814e5542906c55bcc5854ae1/src/view/user-statistic.js#L180
https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/81dc005a1e8b31df814e5542906c55bcc5854ae1/src/view/user-statistic.js#L184
</details>

this._filmsModel.getItems().`filter`((film) => film.watched)

`getStats`(films.`filter`

Три цикла вместо одного: повторное вычисление.

2021-05-24 11:20 UTC, AlexMasterov commented on src/view/user-statistic.js
> +      renderStatisticChart(statisticCtx, stats);
Вместо создания нового объекта `Chart` можно эффективно обновлять старый.

См. [документацию](https://www.chartjs.org/docs/latest/developers/updates.html#updating-charts).

2021-05-24 11:20 UTC, AlexMasterov commented on src/utils/stats.js
> +    genres.forEach((element) => {
`element`

Неудачное название.

2021-05-24 18:15 UTC, AlexMasterov requested changes

2021-05-24 18:15 UTC, AlexMasterov commented on src/const.js
Если открыть попап и добавить комментарий, а потом закрыть и открыть его снова, то при добавление комментариев в консоли появляется ошибка:

```
api.js:75 POST https://14.ecmascript.pages.academy/cinemaddict//comments/0 400 (Bad Request)
```

2021-05-24 18:15 UTC, AlexMasterov commented on src/const.js
См. ТЗ:

> При возникновении ошибки в момент отправки комментария, форма, **содержащая текст комментария должна быть разблокирована** и к ней применяется эффект «покачивание головой»

> **Если запрос на отправку комментария выполнился успешно**, то комментарий должен быть добавлен в список комментариев. Форму добавления комментария **нужно очистить** и разблокировать

Если открыть попап и попробовать отправить комментарий без эмоции, то "возникнет ошибка" и при этом текст комментарий удалится, что не соответствует ТЗ.

2021-05-24 18:26 UTC, AlexMasterov requested changes

2021-05-24 18:26 UTC, AlexMasterov commented on src/const.js
Если открыть попап и в отсутствие сети изменить признак просмотра и т.п., то в консоли появляется _необработанная_ ошибка:
```
Uncaught (in promise) TypeError: Failed to fetch
```
Б2

2021-05-25 09:51 UTC, Filippoussis commented on src/view/main-navigation.js
> +    this._callback.changeType(target.href.match(/[^/#]+$/)[0]);
если честно , то не понятно) иначе я бы специально плохое решение не применял)

2021-05-25 10:32 UTC, Filippoussis commented on src/view/user-statistic.js
> +  const genresCount = Object.values(stats.genres);
numberOfGenres

2021-05-25 10:37 UTC, AlexMasterov commented on src/view/user-statistic.js
> +  const genresCount = Object.values(stats.genres);
> numberOfGenres

Это неверно для анг. языка, а `number`OfGenres нарушает критерий `Б9`.

> См. [похожие замечание](https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/pull/14#discussion_r637811817)

2021-05-25 10:42 UTC, Filippoussis commented on src/utils/stats.js
> +      const isKeyInObject = element in stats.genres;
isKeyInGenres

2021-05-25 10:48 UTC, Filippoussis commented on src/utils/stats.js
> +      const isKeyInObject = element in stats.genres;
stats.genres[item] !== undefined

2021-05-25 10:56 UTC, AlexMasterov commented on src/utils/stats.js
> +      const isKeyInObject = element in stats.genres;
is`Key`In`Genres` — смешение контекстов. 

Все названия здесь уже имеют нагрузку предметной области, а в название отдельной переменной ты меняешь контекст на чистые структуры языка. Так делают начинающие, чтобы себе помочь: добавляют название структур в название переменных вместо того, чтобы выражать их _роли_ и нагружать контекстом предметной области. Без типов мест для _выразительности_ очень мало и опытные разработчики это понимают.

> Проверка на ключ слишком проста, чтобы сохранять её результат в отдельную переменную — это избыточная работа для сборщика мусора. Переменная вообще не нужна

2021-05-25 17:02 UTC, Filippoussis commented on package.json
> +    "chartjs-plugin-datalabels": "0.7.0",
Начиная с версии 1.x, этот плагин больше не регистрируется автоматически .
у меня 0.7, строчку plugins: [ChartDataLabels] - удалил.

2021-05-25 17:27 UTC, Filippoussis commented on src/view/user-statistic.js
> +  const genresCount = Object.values(stats.genres);
попытка №3: genresData ) признаю, что есть проблема с именованием)

2021-05-25 17:56 UTC, Filippoussis commented on src/presenter/film-details-comments.js
> +    newCommentView.setFormPressKeyDownHandler(this._handleFormKeyDown);
я так понимаю должен просто избавиться в названии от привязки к form -> setDocumentPressKeyDownHandler

2021-05-25 18:22 UTC, AlexMasterov commented on src/presenter/film-details-comments.js
> +    newCommentView.setFormPressKeyDownHandler(this._handleFormKeyDown);
Нет, нужно избавиться именно от _деталей реализации_, пример так:

```diff
- newCommentView.setFormPressKeyDownHandler
+ newCommentView.setSubmitHandler
```
```diff
- newCommentView.setFormPressKeyDownHandler
+ newCommentView.setSaveHandler
```
```diff
- newCommentView.setFormPressKeyDownHandler
+ newCommentView.setAddHandler
```

Если "завтра" потребуется добавлять комментарий не по комбинации клавиш, а, например, по нажатию на кнопку, то `FilmDetailsComments` об этом не узнает и в него не потребуется вносить изменения. Отчасти в этом и смысл 😄

2021-05-26 04:18 UTC, Filippoussis commented on src/const.js
плодились обработчики событий, устранил.

2021-05-26 12:51 UTC, AlexMasterov commented
👍🏻

Не буду затягивать с принятием этого задания. 
Вместо ожидания лучше скорее приступай к реализации доп. пунктов ТЗ, в которых тоже будут списки и логика с попап.

> Как освобожусь, проверяю работу попапа и изложу замечания, про которые написал в чате

2021-05-26 12:52 UTC, merged