Время разбивать камни
htmlacademy-ecmascript/1145499-cinemaddict-14 pull request #3
Opened 2021-03-30 14:41 UTC by Filippoussis

---
:mortar_board: [Время разбивать камни](https://up.htmlacademy.ru/ecmascript/14/user/1145499/tasks/3)

:boom: https://htmlacademy-ecmascript.github.io/1145499-cinemaddict-14/3/

2021-03-30 19:59 UTC, AlexMasterov requested changes

2021-03-30 19:59 UTC, AlexMasterov commented on src/const.js
> +const NumberFilms = {
NumberFilm`s`

[`Б7`](https://up.htmlacademy.ru/ecmascript/14/criteries#b7)
> Перечисления названы существительными в единственном числе

<details>
<summary>main.js</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/2cba08217e367947a8d4c7d53a354a8b7c10162f/src/main.js#L31-L32
https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/2cba08217e367947a8d4c7d53a354a8b7c10162f/src/main.js#L41-L42
https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/2cba08217e367947a8d4c7d53a354a8b7c10162f/src/main.js#L49-L50
</details>

Вместо `Number` лучше используй `*Count`: (вообще другой смысл)

```diff
- const NumberFilms = {
+ const FilmListCount = {
```
> Также можно `FilmDisplayCount` или просто `FilmCount`

2021-03-30 19:59 UTC, AlexMasterov commented on src/const.js
> +  BEFOREEND: 'beforeend',
Вроде так читается лучше, что думаешь?
```diff
- BEFOREEND: 'beforeend',
+ BEFORE_END: 'beforeend',
```

2021-03-30 19:59 UTC, AlexMasterov commented on src/main.js
> +
<details>
<summary>main.js</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/2cba08217e367947a8d4c7d53a354a8b7c10162f/src/main.js#L4-L13
</details>

[`Б 10`](https://up.htmlacademy.ru/ecmascript/14/criteries#b10)
> Название функции должно быть глаголом и соответствовать действию, которое выполняет функция

Всё это _функции_, которые _пока_ возвращает сырую разметку (= `Markup`). В следующих заданиях эти функции на основе разметки будет создавать шаблон (= `Template`), а только потом эти функции будут использоваться в классах-компонентов (= `Component`).

Поэтому сейчас нужно в их название добавить глагол, например `get/create*`, и можно сразу суффикс `*Template`:

```diff
- import {filmCardComponent} from './view/film-card';
+ import {getfilmCardTemplate} from './view/film-card';
```
и т.п.

2021-03-30 19:59 UTC, AlexMasterov commented on src/view/main-content.js
> +  return `<section class="films"></section>`;
В строке нет интерполяции и **переноса строки** (= неявный символ `\n`).

> Strings must use singlequote

В этом случае нужно использовать одинарные кавычки `''` (или создать перенос строки 😃).

2021-03-31 04:12 UTC, Filippoussis commented on src/view/main-content.js
> +  return `<section class="films"></section>`;
использовал перенос строки

2021-03-31 04:41 UTC, AlexMasterov commented
👍🏻

2021-03-31 04:41 UTC, merged