Module2 task1
htmlacademy-ecmascript/1145499-cinemaddict-14 pull request #4
Opened 2021-04-04 10:06 UTC by Filippoussis

2021-04-04 12:31 UTC, AlexMasterov requested changes
Многое простых замечаний и слабые решения, но в целом с заданием справился нормально.

Пожалуйста, постарайся учесть замечания, чтобы далее вместо них было время обсуждать и улучшать сами решения.

2021-04-04 12:31 UTC, AlexMasterov commented on src/view/film-details.js
> +          <section class="film-details__controls">
<details>
<summary>view/film-details.js</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/2fe75611118cc572e79cd91312d64c21214251b9/src/view/film-details.js#L105-L114
</details>

Нужно доп. данные фильма для установки значения для `checkbox` (выбор пользователя).

2021-04-04 12:31 UTC, AlexMasterov commented on src/view/film-card.js
> +  const previewGenre = genre.join(' ');
```js
Array.isArray(genre) // true
```
Б9

2021-04-04 12:31 UTC, AlexMasterov commented on src/main.js
> +  return comments.filter((comment) => comment.filmId === film.id).length;
<details>
<summary>mock/comment-data.js</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/2fe75611118cc572e79cd91312d64c21214251b9/src/mock/comment-data.js#L12
</details>

`comment.filmId === film.id`

Избыточные данные об `filmId` в `comment` и их неудачное связывание с `film`, хотя и в данных с сервера будет не лучше 😃

> Для простого получения кол. комментариев к фильму в объекте с данными фильма можно хранить список их `id` (= `film.comments.length`)

2021-04-04 12:31 UTC, AlexMasterov commented on src/view/film-card.js
>        <div class="film-card__controls">
<details>
<summary>view/film-card.js</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/2fe75611118cc572e79cd91312d64c21214251b9/src/view/film-card.js#L24-L28
</details>

Нужно доп. данные фильма для установки значения для `checkbox` (выбор пользователя).

2021-04-04 16:17 UTC, AlexMasterov requested changes

2021-04-04 16:17 UTC, AlexMasterov commented on src/main.js
> +
<details>
<summary>view/film-card.js</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/2fe75611118cc572e79cd91312d64c21214251b9/src/view/film-card.js#L24-L28
</details>

<details>
<summary>view/film-details.js</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/2fe75611118cc572e79cd91312d64c21214251b9/src/view/film-details.js#L105-L114
</details>

Нужно генерировать доп. данные фильма для установки значений для `checkbox` (выбор пользователя).

2021-04-04 17:44 UTC, AlexMasterov requested changes

2021-04-04 17:44 UTC, AlexMasterov commented on src/view/film-card.js
> +  const previewDescription = description.length > LIMIT_CHAR_COMMENTS ? description.slice(0, LIMIT_CHAR_COMMENTS) + '...' : description;
См. внимательно ТЗ:
> Если описание фильма больше 140 символов, то в карточке отображается `139` символов описания и знак многоточие (…)
```js
// const description = 'a'.repeat(140)
previewDescription.length // 140
```
`140` !==`139` 😃

Нужно исправить.

2021-04-04 18:08 UTC, AlexMasterov requested changes

2021-04-05 02:26 UTC, Filippoussis commented on src/const.js
> +export const LIMIT_CHAR_COMMENTS = 140;
я даже себе не смогу объяснить зачем использовал слово COMMENTS) исправил.

2021-04-05 02:30 UTC, Filippoussis commented on src/main.js
> +import {Count} from './mock/const-data';
понятно, исправил.

2021-04-05 02:34 UTC, Filippoussis commented on src/main.js
> +
решение понял, исправил.

2021-04-05 02:38 UTC, Filippoussis commented on src/main.js
> +  renderViewComponent(allFilmsList, getFilmCardTemplate(films[i], commentCount));
исправил на const film = films[i];

2021-04-05 03:04 UTC, Filippoussis commented on src/main.js
> +  const CLASS_NAME_TARGETS = [
перенес в файл const.js c именем OPENING_POPUP_CLASS_NAMES

2021-04-05 03:12 UTC, Filippoussis commented on src/main.js
> +    document.addEventListener('keydown', handlePressEsc);
изменил на buttonEscPressHandler

2021-04-05 03:16 UTC, Filippoussis commented on src/main.js
> +    const commentsFilm = comments.filter((comment) => comment.filmId === selectedFilm.id);
исправил на filmComments

2021-04-05 03:19 UTC, Filippoussis commented on src/view/film-details.js
> +  const commentsCount = commentsFilm.length;
исправил на filmComments

2021-04-05 03:32 UTC, Filippoussis commented on src/view/film-card.js
> +  const previewGenre = genre.join(' ');
genre с сервера приходит, для моков использовал GENRES

2021-04-05 03:35 UTC, Filippoussis commented on src/view/film-details.js
> +  const genreTemplate = renderGenreTemplate(genre);
genre с сервера приходит, для моков использовал GENRES

2021-04-05 03:44 UTC, Filippoussis commented on src/view/profile.js
> +  const watchedFilmsCount = films.filter((film) => film.isWatched === true).length;
исправил на (film) => film.isWatched

2021-04-05 03:49 UTC, Filippoussis commented on src/view/film-details.js
> +  const commentsList = commentsCount ? renderCommentsTemplate(commentsFilm) : '';
исправил на commentsCount > 0

2021-04-05 03:52 UTC, Filippoussis commented on src/utils/common.js
> +/**
переименовал)

2021-04-05 03:53 UTC, Filippoussis commented on src/view/footer-statistics.js
> +  const filmsNumber = films.length;
переименовал на filmCount

2021-04-05 03:57 UTC, Filippoussis commented on src/view/film-details.js
> +  return comments.map((comment) => getCommentTemplate(comment)).join('');
спасибо, отрефакторил

2021-04-05 04:10 UTC, Filippoussis commented on src/view/film-card.js
> +  const previewDescription = description.length > LIMIT_CHAR_COMMENTS ? description.slice(0, LIMIT_CHAR_COMMENTS) + '...' : description;
не внимательно прочитал этот кусок ТЗ, каюсь)
исправил на DESCRIPTION_MAX_LENGTH ? description.slice(0, DESCRIPTION_MAX_LENGTH - 1) + '\u2026'

2021-04-05 08:18 UTC, AlexMasterov commented on src/main.js
> +    document.addEventListener('keydown', handlePressEsc);
> изменил на buttonEscPressHandler

`keydown` !== buttonEsc`Press`Handler

Название _события_ (= `keydown`) должно полностью и точно повторятся в имени обработчика.

> Событие `Press` (= `keypress`) давно [считается устаревшим](https://developer.mozilla.org/en-US/docs/Web/API/Document/keypress_event); вместо него следует использовать `keydown`

2021-04-05 08:21 UTC, AlexMasterov commented on src/view/film-details.js
> +  const genreTemplate = renderGenreTemplate(genre);
> genre с сервера приходит, для моков использовал GENRES

При парсинге данных с сервера название массива `genre` потребуется исправить на множ. число.

2021-04-05 08:23 UTC, AlexMasterov commented on src/utils/common.js
> +/**
> переименовал)

Сейчас в модуле только функции для генерации данных.

Потом после реализации получения данных с сервера модули для генерации данных станут не нужны и так их будет проще удалить.

2021-04-05 08:33 UTC, AlexMasterov commented on src/view/film-card.js
> +  const previewDescription = description.length > LIMIT_CHAR_COMMENTS ? description.slice(0, LIMIT_CHAR_COMMENTS) + '...' : description;
<details>
<summary>Покажи что еще можно сделать</summary>

```js
// utils.js
export const getTruncatedText = (text, maxLength) =>
  text.length > maxLength
    ? `${text.slice(0, maxLength - 1)}\u2026`
    : text;
```
```js
// view/film-card.js
const previewDescription = getTruncatedText(description, DESCRIPTION_MAX_LENGTH);
```
😃
</details>

2021-04-05 08:59 UTC, AlexMasterov commented on src/view/profile.js
> +  const watchedFilmsCount = films.filter((film) => film.isWatched === true).length;
> Исправление с неявным сравнением на булево значение негативно скажется на скорости цикла, но это внутренние детали реализации движков языка

<details>
<summary>Проверим</summary>

<details>
<summary>V8-8.4.371.19-node.12 (пример из демо)</summary>

```js
const createTask = () => ({ isArchive: true });

const tasks = new Array(100).fill(null).map(createTask);
tasks[50] = { isArchive: false };

const benchEvery = () => tasks.every((task) => task.isArchive);
const benchEveryTrue = () => tasks.every((task) => task.isArchive === true);
const benchSome = () => tasks.some((task) => task.isArchive === false);
```
```
.some         x 24,425,459 ops/sec ±0.20%
.everyTrue    x 24,328,456 ops/sec ±0.27%
.every        x 11,813,976 ops/sec ±1.21%
```
</details>

<details>
<summary>V8-6.395.17-node.27</summary>

```js
const createFilm = () => ({ isWatched: true });

const films = new Array(100).fill(null).map(createFilm);
films[50] = { isWatched: false };

const benchFn1 = () => films.filter((film) => film.isWatched);
const benchFn2 = () => films.filter((film) => film.isWatched === true);
const benchFn3 = () => films.filter((film) => film.isWatched == true);
```
```
.filter === true x 2,495,484 ops/sec ±1.37%
.filter          x 2,301,277 ops/sec ±0.51%
.filter == true  x 1,786,224 ops/sec ±0.53%
```
</details>

В новых версиях движка JS почти нет отличий (только погрешность самого бенчмарка).
</details>

2021-04-05 11:26 UTC, AlexMasterov commented on src/main.js
> +
@Filippoussis, пока достаточно сделать только для:

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/2fe75611118cc572e79cd91312d64c21214251b9/src/main.js#L64

Элемент с popup непостоянен, он добавляется в DOM во время выполнения и удаляется при закрытии. Тут ничего трогать не нужно.

2021-04-06 09:02 UTC, Filippoussis commented on src/main.js
> +    document.addEventListener('keydown', handlePressEsc);
теперь понял значение keydown !== buttonEscPressHandler) поправил

2021-04-06 09:53 UTC, AlexMasterov approved these changes
👍🏻

Для задания сделано достаточно, а для решений сверх критериев и вопросов используй консультацию. Необязательные замечания в остатке постарайся учесть при выполнении следующего задания

2021-04-06 09:53 UTC, AlexMasterov commented on src/view/filter.js
> +  const favoriteCount = films.reduce((sum, {isFavorite}) => sum + isFavorite, 0);
У тебя получилось убрать избыточное создание трех массивов, но получение счетчиков все еще занимает три цикла (три полных итерации по массиву `films`).

Но см. снова [комментарий](https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/pull/4#discussion_r606784576):

[`Б 34`](https://up.htmlacademy.ru/ecmascript/14/criteries#b34)
> Если задачу можно решить за один проход по циклу, вместо нескольких она **должна быть решена за один**

<details>
<summary>Подскажи, как это можно сделать</summary>

Нужно использовать _один_ [Array.p.reduce](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce), которому в качестве акуммулятора можно задать объект: `{ isWatchlist: 0, isWatched: 0, isFavorite: 0 }`, а при итерации использовать его ключи в качестве счетчиков. Этот объект вернуть, как результат.
</details>

2021-04-06 09:53 UTC, AlexMasterov commented on src/view/profile.js
> +  const watchedFilmsCount = films.filter((film) => film.isWatched).length;
🤔

2021-04-06 09:53 UTC, AlexMasterov commented on src/const.js
> +export const getProfileRank = (watchedFilmsCount) => {
`const.js` + `getProfileRank`

[`Б 27`](https://up.htmlacademy.ru/ecmascript/14/criteries#b27)
> Название модуля соответствует его содержимому

Это функции нужно найти другой модуль.

<details>
<summary>const.js</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/19b55c09ab71df35e14f50b801b3a3ecf1feb7f2/src/const.js#L19-L34
</details>

Специализированные константы можно забрать с функцией.

2021-04-06 09:53 UTC, AlexMasterov commented on src/const.js
> +export const getProfileRank = (watchedFilmsCount) => {
<details>
<summary>getProfileRank</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/19b55c09ab71df35e14f50b801b3a3ecf1feb7f2/src/const.js#L36-L47
</details>


Вместо этого попробуй использовать: `[{ title, rating }, ...]` + [Array.p.`find`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/find).

Если получится, то по итогу, желательно всё обернуть в функцию и экспортировать только её.

2021-04-06 09:53 UTC, AlexMasterov commented on src/const.js
> +export const addAttributeChecked = (isContolActive) => {
<details>
<summary>const.js</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/19b55c09ab71df35e14f50b801b3a3ecf1feb7f2/src/const.js#L54-L60
</details>

[`Б 27`](https://up.htmlacademy.ru/ecmascript/14/criteries#b27)
> Название модуля соответствует его содержимому

Этим функциям нужно найти другой модуль.

2021-04-06 09:53 UTC, AlexMasterov commented on src/const.js
> +  CLASS_NAME: 'film-card__controls-item--active',
<details>
<summary>const.js</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/19b55c09ab71df35e14f50b801b3a3ecf1feb7f2/src/const.js#L13-L17
https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/19b55c09ab71df35e14f50b801b3a3ecf1feb7f2/src/const.js#L51
</details>

Эти классы _не_ используются во всем проекте, но находятся в корневом `const.js`.

2021-04-06 09:53 UTC, AlexMasterov commented on src/view/film-details.js
> +            <label for="watchlist" class="film-details__control-label film-details__control-label--watchlist">Add to watchlist</label>
<details>
<summary>const.js</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/19b55c09ab71df35e14f50b801b3a3ecf1feb7f2/src/const.js#L49-L52
https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/19b55c09ab71df35e14f50b801b3a3ecf1feb7f2/src/const.js#L54-L56
https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/19b55c09ab71df35e14f50b801b3a3ecf1feb7f2/src/view/film-details.js#L51-L53
</details>

Вместо этого лучше попробуй красиво переиспользовать разметку:
```js
${createControlTemplate('watchlist', 'Add to watchlist', isCheckedWatchlist)}
```

2021-04-06 09:53 UTC, merged

2021-04-10 16:49 UTC, Filippoussis commented on src/view/filter.js
> +  const favoriteCount = films.reduce((sum, {isFavorite}) => sum + isFavorite, 0);
спасибо, вроде получилось.

2021-04-10 16:51 UTC, Filippoussis commented on src/const.js
> +export const getProfileRank = (watchedFilmsCount) => {
пока в работе)