Module3 task1
htmlacademy-ecmascript/1145499-cinemaddict-14 pull request #5
Opened 2021-04-10 16:48 UTC by Filippoussis

2021-04-10 19:05 UTC, AlexMasterov requested changes

2021-04-10 19:05 UTC, AlexMasterov commented on src/main.js
> +    const filmDetailsComponent = new FilmDetailsView(selectedFilm, filmComments);
Для представлений советую использовать суффикс `View`, чтобы при появление `Presenter` и `Model` не запутаться в их инстансах.

> `Component` — это рудимент с прошлых интенсивах

2021-04-11 04:27 UTC, Filippoussis commented on src/view/sort.js
> +export default class Sort {
поменял на FilmsFilter и FilmsSort

2021-04-11 04:30 UTC, Filippoussis commented on src/main.js
> +    const buttonCloseComponent = filmDetailsComponent.getElement().querySelector(ClassName.CLOSE_BTN);
спасибо за замечания, с названиями видимо туго) буду больше уделять им внимания, исправил.

2021-04-11 04:31 UTC, Filippoussis commented on src/view/filter.js
> +    this._filterResult = filterResult;
исправил на FilmsFilter

2021-04-11 06:04 UTC, Filippoussis commented on src/utils/render.js
> +  const newElement = document.createElement('div');
исправил.

2021-04-11 06:11 UTC, Filippoussis commented on src/view/films-total.js
> +    this._filmsTotalCount = filmsTotalCount;
исправил

2021-04-11 06:36 UTC, Filippoussis commented on src/main.js
> +      document.querySelector('body').classList.remove(ClassName.NO_SCROLL);
исправил, решил обойтись без поиска вообще, через прямое обращение к body как при добавлении, так и удалении класса

2021-04-11 06:47 UTC, Filippoussis commented on src/main.js
> +    const filmDetailsComponent = new FilmDetailsView(selectedFilm, filmComments);
заменил везде по коду Component на View ( там где нужно 🙂)

2021-04-11 08:29 UTC, Filippoussis commented on src/view/film-card.js
> +const createControlTemplate = (id, text, isMod) => {
спасибо, сделал.

2021-04-11 09:22 UTC, Filippoussis commented on src/utils/render.js
> +  switch (place) {
default: throw new Error('place должен быть InsertPlace.BEFORE_END или InsertPlace.AFTER_END');

2021-04-11 17:54 UTC, AlexMasterov requested changes
Нужно исправить мелкие замечания, которые обязательны к исправлению. 

После можно принимать задание 😃

2021-04-11 17:54 UTC, AlexMasterov commented on src/utils/rating.js
> +const profileRatings = [
<details>
<summary>profileRatings</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/f7e30c022e622b1b36f38e875de0d1850481fc52/src/utils/rating.js#L1-L21
</details>

Б5

Нужно записать название массива в формате константы.

2021-04-11 17:54 UTC, AlexMasterov commented on src/utils/render.js
> +    default: throw new Error('place должен быть InsertPlace.BEFORE_END или InsertPlace.AFTER_END');
[`Б 13`](https://up.htmlacademy.ru/ecmascript/14/criteries#b13)
> Используются обязательные блоки кода

> таких как for, while, if, `switch`, function, блок кода используется обязательно, **даже если инструкция состоит из одной строчки**

2021-04-11 17:54 UTC, AlexMasterov commented on src/view/film-card.js
> +  const classMod = isActive === true ? CLASS_MOD_NAME : '';
`isActive === true`

```js
typeof isActive // boolean
```

[`Д 13`](https://up.htmlacademy.ru/ecmascript/14/criteries#d13)
> Отсутствуют лишние приведения и проверки типов

> То же касается и избыточной проверки булевой переменной

В этом случае можно убрать явную проверку: `=== true`.

2021-04-11 17:54 UTC, AlexMasterov commented on src/view/film-details.js
> +const addAttributeChecked = (isContolActive) => {
<details>
<summary>addAttributeChecked</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/f7e30c022e622b1b36f38e875de0d1850481fc52/src/view/film-details.js#L4-L6
</details>

Кстати, функция сама ничего не _добавляет_ (= `add`), а только по условию _возвращает_ строку.

> Очень надеялся, что такая функция пропадет естественным образом

[`Б 10`](https://up.htmlacademy.ru/ecmascript/14/criteries#b10)
> Название функции должно быть глаголом и соответствовать действию, которое выполняет функция

> Например, **можно использовать глагол `get` для функций или методов, которые что-то возвращают**

2021-04-11 17:54 UTC, AlexMasterov commented on src/view/films-total.js
> +const createFilmsTotalTemplate = (filmsTotalCount) => {
create`FilmsTotal`Template = (`filmsTotal`Count) => { ... } 🤔

```diff
- const createFilmsTotalTemplate = (filmsTotalCount) => {
+ const createFilmsTotalTemplate = (count) => {
```

2021-04-11 17:54 UTC, AlexMasterov commented on src/utils/rating.js
> +  }, {
<details>
<summary>utils/rating.js</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/f7e30c022e622b1b36f38e875de0d1850481fc52/src/utils/rating.js#L8
https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/f7e30c022e622b1b36f38e875de0d1850481fc52/src/utils/rating.js#L14
</details>

Желательно перенести создание объектов на новую строку или записать в одну.

Такой подход даёт понятную разницу при просмотре изменении в Гите. Например, при удаление или добавление нового объекта изменения в Гите не затронут ближайший объект.

> См. также стилевой гайд от [Airbnb](https://github.com/leonidlebedev/javascript-airbnb#commas--dangling)

2021-04-11 17:54 UTC, AlexMasterov commented on src/utils/rating.js
> +  return value !== 0 ? (profileRatings.find((item) => value >= item.range.min && value <= item.range.max)).title : '';
Желательно стараться подобное упрощать:
```diff
- return value !== 0 ?
+ return value > 0 ?
```
> Это также учтет: `value <= -1`

2021-04-11 17:54 UTC, AlexMasterov commented on src/utils/rating.js
> +export const getProfileRank = (value) => {
<details>
<summary>utils/rating.js</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/f7e30c022e622b1b36f38e875de0d1850481fc52/src/utils/rating.js#L1-L21
https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/f7e30c022e622b1b36f38e875de0d1850481fc52/src/utils/rating.js#L23-L25
</details>

<details>
<summary>Покажи, как можно упростить</summary>

```js
const RATING_TITLES = [
  {rating: 21, title: 'Movie Buff'},
  {rating: 11, title: 'Fan'},
  {rating: 1, title: 'Novice'},
  {rating: 0, title: ''}
];

const getRatingTitle = (value) => RATING_TITLES
  .find(({rating}) => rating <= value)
  .title || '';
```
> `RATING_TITLES` -> get`RatingTitle`, без привязки к `ProfileRank`, т.е. одному конкретному компоненту
</details>

2021-04-11 17:54 UTC, AlexMasterov commented on src/utils/render.js
> +    default: throw new Error('place должен быть InsertPlace.BEFORE_END или InsertPlace.AFTER_END');
<details>
<summary>render</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/f7e30c022e622b1b36f38e875de0d1850481fc52/src/utils/render.js#L11
</details>

<details>
<summary>Покажи свои варианты</summary>

```js
throw new Error(`Unknown render position: ${place}`);
```
```js
throw new Error(
  `Unknown render position: ${place}. Possible values: ${Object.values(InsertPlace).join(', ')}`
);
```
</details>

2021-04-11 18:32 UTC, Filippoussis commented on src/utils/filter.js
> +    if (isFavorite) stats.favoriteCount += Number(isFavorite);
исправил

2021-04-11 18:32 UTC, Filippoussis commented on src/utils/filter.js
> +    if (isFavorite) stats.favoriteCount += Number(isFavorite);
исправил

2021-04-11 18:33 UTC, Filippoussis commented on src/utils/rating.js
> +const profileRatings = [
исправил

2021-04-11 18:44 UTC, Filippoussis commented on src/utils/rating.js
> +  }, {
исправил

2021-04-11 18:53 UTC, Filippoussis commented on src/utils/rating.js
> +  return value !== 0 ? (profileRatings.find((item) => value >= item.range.min && value <= item.range.max)).title : '';
принято

2021-04-11 18:54 UTC, Filippoussis commented on src/utils/rating.js
> +export const getProfileRank = (value) => {
разобрал решение, использовал у себя)

2021-04-11 19:01 UTC, Filippoussis commented on src/view/films-total.js
> +const createFilmsTotalTemplate = (filmsTotalCount) => {
исправил

2021-04-11 19:07 UTC, Filippoussis commented on src/view/film-card.js
> +  const classMod = isActive === true ? CLASS_MOD_NAME : '';
исправил

2021-04-11 19:18 UTC, Filippoussis commented on src/view/film-details.js
> +const addAttributeChecked = (isContolActive) => {
пересмотрел подход, вообще ранее думал что не следует функцию в разметку ставить.

2021-04-11 19:19 UTC, Filippoussis commented on src/utils/render.js
> +    default: throw new Error('place должен быть InsertPlace.BEFORE_END или InsertPlace.AFTER_END');
исправил

2021-04-11 19:25 UTC, Filippoussis commented on src/utils/render.js
> +    default: throw new Error('place должен быть InsertPlace.BEFORE_END или InsertPlace.AFTER_END');
спасибо, воспользовался твоим вариантом)

2021-04-11 19:30 UTC, AlexMasterov commented
👍🏻

2021-04-11 19:30 UTC, merged