Module5 task1
htmlacademy-ecmascript/1145499-cinemaddict-14 pull request #8
Opened 2021-04-22 13:02 UTC by Filippoussis

2021-04-22 14:47 UTC, AlexMasterov requested changes

2021-04-22 14:47 UTC, AlexMasterov commented on src/presenter/film-details.js
> +    this._film = newItem;
<details>
<summary>presenter/film-details.js</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/c26c04f309ba5cddc3fe73ada9912b1f0e17193d/src/presenter/film-details.js#L106
</details>

Этот презентер _неявно_ (для род. презентера) изменяет своё состояние.

2021-04-22 14:47 UTC, AlexMasterov commented on src/presenter/screen.js
> +      return;
<details>
<summary>presenter/screen.js</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/c26c04f309ba5cddc3fe73ada9912b1f0e17193d/src/presenter/screen.js#L54-L56
</details>

В этом месте явный (пустой) `return` не требуется.

Б18

2021-04-22 14:47 UTC, AlexMasterov commented on src/presenter/screen.js
> +    if (filmsTotalCount !== 0) {
Опять усложняешь 😃
```diff
- if (filmsTotalCount !== 0) {
+ if (filmsTotalCount > 0) {
```

2021-04-22 14:47 UTC, AlexMasterov commented on src/utils/render.js
> +  if (parent === null || oldChild === null || newChild === null) {
<details>
<summary>replace</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/c26c04f309ba5cddc3fe73ada9912b1f0e17193d/src/utils/render.js#L46-L56
</details>

Обращение к oldChild.`parentElement` происходит _до_ проверки `oldChild` на `null`.

Пример:
```js
replace(null, null);
```
```
render.js:54 Uncaught TypeError: Cannot read property 'parentElement' of null
```

[`Б 2`](https://up.htmlacademy.ru/ecmascript/14/criteries#b2)
> При выполнении кода не возникает необработанных ошибок

2021-04-22 14:47 UTC, AlexMasterov commented on src/utils/update.js
> +export const updateItem = (items, update) => {
<details>
<summary>utils/update.js</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/c26c04f309ba5cddc3fe73ada9912b1f0e17193d/src/utils/update.js#L2
</details>

```diff
- export const updateItem = (items, update) => {
+ export const updateItemById = (items, update) => {
```

2021-04-22 14:47 UTC, AlexMasterov commented on src/view/film-card.js
> +    this._callback.cardClick = callback;
this._callback.card`Click`

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/c26c04f309ba5cddc3fe73ada9912b1f0e17193d/src/view/film-card.js#L98

[`Б 10`](https://up.htmlacademy.ru/ecmascript/14/criteries#b10)
> Название метода должно быть глаголом и соответствовать действию, которое выполняет метод

Нужно в название метода поставить `click` в начало:

 
```diff
- this._callback.cardClick = callback;
+ this._callback.clickCard = callback;
```

2021-04-22 14:47 UTC, AlexMasterov commented on src/view/film-card.js
> +    this._callback.watchlistClick = callback;
this._callback.watchlist`Click`

Б10

2021-04-22 14:47 UTC, AlexMasterov commented on src/view/film-card.js
> +    this._callback.watchedClick = callback;
this._callback.watched`Click`

Б10

2021-04-22 14:47 UTC, AlexMasterov commented on src/view/film-card.js
> +    this._callback.favoriteClick = callback;
this._callback.favorite`Click`

Б10

2021-04-22 14:47 UTC, AlexMasterov commented on src/view/film-card.js
> +    this._callback.favoriteClick(evt);
this._callback.favoriteClick(`evt`)

Нужно проверить, что в коллбэке объект события `evt` использоваться.

~Б18

2021-04-22 14:47 UTC, AlexMasterov commented on src/view/film-card.js
> +      .addEventListener('click', this._watchlistClickHandler);
.film-card__controls-item--`add-to-watchlist` + `click` !== this._`watchlist`ClickHandler

Д4

2021-04-22 14:47 UTC, AlexMasterov commented on src/view/film-card.js
> +      .addEventListener('click', this._watchedClickHandler);
.film-card__controls-item--`mark-as-watched` + `click` !== this._`watched`ClickHandler)

Д4

2021-04-22 14:47 UTC, AlexMasterov commented on src/view/film-details.js
> +    this._callback.watchlistChange = callback;
this._callback.watchlist`Change` = callback;

Б10

2021-04-22 14:47 UTC, AlexMasterov commented on src/view/film-details.js
> +    this._callback.watchedChange = callback;
this._callback.watched`Change`

Б10

2021-04-22 14:47 UTC, AlexMasterov commented on src/view/film-details.js
> +    this._callback.favoriteChange = callback;
this._callback.favorite`Change`

Б10

2021-04-23 02:38 UTC, Filippoussis commented on src/presenter/film-details.js
> +    this._film = newItem;
в init использовал this._film = film.slice();

2021-04-23 12:55 UTC, Filippoussis commented on src/utils/render.js
> +  if (parent === null || oldChild === null || newChild === null) {
разделил условие на 2 части:
if (parent === null) {
    throw new Error('Missing parent for elements');
  }

2021-04-23 16:24 UTC, Filippoussis commented on src/view/film-card.js
> +    this._callback.favoriteClick(evt);
убрал ненужные evt

2021-04-23 16:25 UTC, Filippoussis commented on src/presenter/film-card.js
> +    this._filmContainer = container;
пока не нашел решения) чуть позже попробую

2021-04-23 16:27 UTC, Filippoussis commented on src/presenter/all-films.js
> +    render(this._allFilmsView, this._filmsContainerView);
попробовал DocumentFragment, не получилось из-за обновления карточек, усложнялась реализация, в итоге минимизировал отрисовку путем рендера контейнера после рендера карточек

2021-04-23 17:40 UTC, AlexMasterov commented on src/presenter/all-films.js
> +    render(this._allFilmsView, this._filmsContainerView);
К сожалению, сейчас не могу проверить, но по коду вижу, что проблема не решена 😃

> **попробовал `DocumentFragment`**, не получилось из-за обновления карточек, усложнялась реализация

<details>
<summary>utils/render.js | render</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/803771d2a3140a0c4cf7cd8b4b6f8d5a778bf4bd/src/utils/render.js#L16
</details>

Для добавления компонентов карточек в узлы `DOM` используется функция `render`, которая использует метод [ParentNode.`append`](https://developer.mozilla.org/ru/docs/orphaned/Web/API/ParentNode/append). Если посмотреть его исходный код в популярном браузере `Chromium`, то можно увидеть, что он уже неявно использует `DocumentFragment`.

<details>
<summary>Покажи исходный код метода .append</summary>

[`third_party/blink/renderer/core/dom/node.cc`](https://source.chromium.org/chromium/chromium/src/+/refs/tags/92.0.4486.2:third_party/blink/renderer/core/dom/node.cc;l=878-889):
```cpp
void Node::Append(/* ... **/) {
  // ...
  if (Node* node =
          ConvertNodesIntoNode(this, nodes, GetDocument(), exception_state))
    this_node->AppendChild(node, exception_state);
}
```
[`third_party/blink/renderer/core/dom/node.c`](https://source.chromium.org/chromium/chromium/src/+/refs/tags/92.0.4486.2:third_party/blink/renderer/core/dom/node.cc;l=838-861;drc=1779d9d766971b9c6646eac47c2ec68d15d6fd9f):
```cpp
static Node* ConvertNodesIntoNode(/* ... **/)
  // ...
  Node* fragment = DocumentFragment::Create(document);
  for (const NodeOrStringOrTrustedScript& node_or_string_or_trusted_script :
       nodes) {
    Node* node = NodeOrStringToNode(node_or_string_or_trusted_script, document,
                                    needs_check, exception_state);
    if (node)
      fragment->appendChild(node, exception_state);
    if (exception_state.HadException())
      return nullptr;
  }
  return fragment;
```
</details>

Проблема в том, что сама функция `render` этого не учитывает и мы добавляем элементы _по одному_.

> в итоге минимизировал отрисовку путем рендера контейнера после рендера карточек

<details>
<summary>presenter/all-films.js</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/803771d2a3140a0c4cf7cd8b4b6f8d5a778bf4bd/src/presenter/all-films.js#L31
</details>

<details>
<summary>presenter/screen.js</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/803771d2a3140a0c4cf7cd8b4b6f8d5a778bf4bd/src/presenter/screen.js#L30-L32
</details>

Нужно `render` в целевой `this._container` делать не в конструкторе, а в методе `.init` или глубже, когда Презентер полностью собрал в свой элемент элементы карточек.

2021-04-23 17:43 UTC, AlexMasterov commented on src/presenter/film-card.js
> +    this._filmContainer = container;
Достаточно реализовать это:
```js
// constructor
this._containerView = containerView;

// init
if (this._filmContainer.contains(prevFilmCardView)) { ... }
```

2021-04-23 17:46 UTC, AlexMasterov commented
[LGTM](https://coub.com/view/29wef6)!

2021-04-23 17:46 UTC, merged

2021-04-23 17:56 UTC, AlexMasterov commented on src/presenter/film-card.js
> +    this._filmContainer = container;
> пока не нашел решения

Будь уверен, что даю только посильные замечания к исправлению, которые обсуждаются на лайв-лекциях. Поэтому не нужно искать "сложных" решений, а порой лучше уточнить 😃