Module5 task2
htmlacademy-ecmascript/1145499-cinemaddict-14 pull request #9
Opened 2021-04-26 14:12 UTC by Filippoussis

2021-04-26 14:22 UTC, AlexMasterov requested changes
Нужно немного доработать.

2021-04-26 14:22 UTC, AlexMasterov commented on src/view/films-sort.js
> +      <li><a href="#" class="sort__button sort__button--active" data-sort-type="${SortType.DEFAULT}">Sort by default</a></li>
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/116098007-62178f00-a6b3-11eb-9732-6739c2ee49c6.png)

</details>

При переключение кнопок сортировки активной всегда остается `SortType.DEFAULT`.

См. [`ТЗ`](https://up.htmlacademy.ru/ecmascript/14/project/cinemaddict#other):
> В зависимости от состояния, некоторым элементам управления применяются соответствующие классы оформления. Например, активный фильтр и т. д. Примеры доступны в директории с вёрсткой (`markup`)

> Активной кнопке нужно добавлять спец. класс: `sort__button--active`

2021-04-27 22:31 UTC, Filippoussis commented on src/view/films-sort.js
> +      <li><a href="#" class="sort__button sort__button--active" data-sort-type="${SortType.DEFAULT}">Sort by default</a></li>
реализовал через DOM, видел 2 вариант через перерисовку SortComponent, но он показался более избыточным решением чтоли.

2021-04-27 22:37 UTC, AlexMasterov approved these changes
Пожалуйста, при выполнении следующего задания доработай решение с добавлением и удалением класса для кнопок сортировки.

2021-04-27 22:37 UTC, AlexMasterov commented on src/view/films-sort.js
> +      evt.target.classList.add('sort__button--active');
<details>
<summary>view/films-sort.js</summary>

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/8f623fc60530a80a9cf402388bf001b0bc6d0bf3/src/view/films-sort.js#L26-L29

https://github.com/htmlacademy-ecmascript/1145499-cinemaddict-14/blob/8f623fc60530a80a9cf402388bf001b0bc6d0bf3/src/view/films-sort.js#L44-L45
</details>

[`Д 21`](https://up.htmlacademy.ru/ecmascript/14/criteries#d21)
> Изменения применяются точечно

> <...> **при удалении классов с DOM-элемента, не производится попытка удалить все возможные классы**, если можно убрать лишь тот, который действительно установлен на DOM-элементе в данный момент

Нужно доработать решение.

2021-04-27 22:37 UTC, merged

2021-04-27 22:40 UTC, AlexMasterov commented on src/view/films-sort.js
> +      <li><a href="#" class="sort__button sort__button--active" data-sort-type="${SortType.DEFAULT}">Sort by default</a></li>
Попробуй найти элемент с активным классом `sort__button--active` с помощью `.querySelector` и при его наличие удалить сам класс.

2021-04-27 22:49 UTC, Filippoussis commented on src/view/films-sort.js
> +      evt.target.classList.add('sort__button--active');
this.getElement().querySelector('.sort__button--active').classList.remove('sort__button--active');

2021-04-27 22:52 UTC, Filippoussis commented on src/view/films-sort.js
> +      <li><a href="#" class="sort__button sort__button--active" data-sort-type="${SortType.DEFAULT}">Sort by default</a></li>
так и решил сам)
this.getElement().querySelector('.sort__button--active').classList.remove('sort__button--active');

2021-04-27 22:53 UTC, Filippoussis commented on src/view/films-sort.js
> +      <li><a href="#" class="sort__button sort__button--active" data-sort-type="${SortType.DEFAULT}">Sort by default</a></li>
так и решил сам)
this.getElement().querySelector('.sort__button--active').classList.remove('sort__button--active');

2021-04-27 22:56 UTC, AlexMasterov commented on src/view/films-sort.js
> +      evt.target.classList.add('sort__button--active');
> this.getElement().querySelector('.sort__button--active').classList.remove('sort__button--active');

Еще бы уточнить класс, с которого начинается поиск, а то сейчас все теги обходит 😃

Также учти, что в отсутствие класса `.querySelector` вернет `null` и тогда обращение к его свойству `.classList` (= `null.classList`) выбросит исключение (ошибку). Но в текущей реализации класса такой ситуации возникнуть _вроде_ не может — шаблон всегда генерируется в этим классом.

2021-04-27 23:03 UTC, Filippoussis commented on src/view/films-sort.js
> +      evt.target.classList.add('sort__button--active');
точно, this.getElement().querySelector('.sort__button.sort__button--active').classList.remove('sort__button--active');